// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/lib/types/database';
import { config } from '@/config';

// Create Supabase client
export const supabase = createClient<Database>(config.supabaseUrl, config.supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Initialize with connection check
const checkConnection = async () => {
  try {
    // Perform a lightweight query to check the connection.
    // Using .limit(1) and .select('count') for minimal data transfer.
    const storedValue = localStorage.getItem('isTestMode');
    const isTestMode = storedValue !== null ? JSON.parse(storedValue) : true;
    const memoriesTable = isTestMode ? 'test_memories' : 'memories';
    
    const { error } = await supabase.from(memoriesTable).select('count').limit(1);
    if (error) throw error;
    console.log('Supabase connection successful.');
    return true;
  } catch (e: any) {
    console.warn(`Supabase connection check failed: ${e.message}`);
    return false;
  }
};

(async () => {
  await checkConnection();
})();
